api:
  prefix: /api

spring:
  application:
    name: orchidbe

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${SQL_SERVER_HOST}:${SQL_SERVER_PORT};databaseName=${SQL_SERVER_DB};trustServerCertificate=true
    username: ${SQL_SERVER_USER}
    password: ${SQL_SERVER_PASS}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

# Logging configuration

jwt:
  expiration: ${JWT_EXPIRATION} #1 day = 1 * 24 * 60 * 60
  expiration-refresh-token: ${JWT_REFRESH_TOKEN_EXPIRATION} #60 days = 60 * 24 * 60 * 60
  secretKey: ${JWT_SECRET_KEY}