spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:orchid_db}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASS:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # Flyway configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    baseline-description: "Baseline init for notification service"
    baseline-version: 0
